force-app/main/default/objects/Sprout_Social_Data_Event__c/Sprout_Social_Data_Event__c.object-meta.xml
<CustomObject>
    <label>Sprout Social Data Event</label>
    <nameField>
        <displayFormat>DE-{0000}</displayFormat>
        <label>Sprout Social Data Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sprout Social Data Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Customer_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Profile_Id__c</fullName>
    <externalId>true</externalId>
    <label>Customer Profile Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Media_Provider__c.field-meta.xml
<CustomField>
    <fullName>Media_Provider__c</fullName>
    <label>Media Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Parent_GUID__c.field-meta.xml
<CustomField>
    <fullName>Parent_GUID__c</fullName>
    <externalId>true</externalId>
    <label>Parent GUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Persona_Author_Labels__c.field-meta.xml
<CustomField>
    <fullName>Persona_Author_Labels__c</fullName>
    <label>Persona Author Labels</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Persona_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Persona_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Persona External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Persona_External_Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Persona_External_Picture_URL__c</fullName>
    <label>Persona External Picture URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Persona_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Persona_First_Name__c</fullName>
    <label>Persona First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Persona_Followers__c.field-meta.xml
<CustomField>
    <fullName>Persona_Followers__c</fullName>
    <label>Persona Followers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Persona_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Persona_Last_Name__c</fullName>
    <label>Persona Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Persona_Name__c.field-meta.xml
<CustomField>
    <fullName>Persona_Name__c</fullName>
    <label>Persona Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Persona_Profile_URL__c.field-meta.xml
<CustomField>
    <fullName>Persona_Profile_URL__c</fullName>
    <label>Persona Profile URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Persona_Provider__c.field-meta.xml
<CustomField>
    <fullName>Persona_Provider__c</fullName>
    <label>Persona Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Persona_Real_Name__c.field-meta.xml
<CustomField>
    <fullName>Persona_Real_Name__c</fullName>
    <label>Persona Real Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Post_Content__c.field-meta.xml
<CustomField>
    <fullName>Post_Content__c</fullName>
    <label>Post Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Post_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Post_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>Post External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Post_Handle__c.field-meta.xml
<CustomField>
    <fullName>Post_Handle__c</fullName>
    <label>Post Handle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Post_Name__c.field-meta.xml
<CustomField>
    <fullName>Post_Name__c</fullName>
    <label>Post Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Post_Provider__c.field-meta.xml
<CustomField>
    <fullName>Post_Provider__c</fullName>
    <label>Post Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Post_Recipient__c.field-meta.xml
<CustomField>
    <fullName>Post_Recipient__c</fullName>
    <label>Post Recipient</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Post_Tags__c.field-meta.xml
<CustomField>
    <fullName>Post_Tags__c</fullName>
    <label>Post Tags</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Post_URL__c.field-meta.xml
<CustomField>
    <fullName>Post_URL__c</fullName>
    <label>Post URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Posted_At__c.field-meta.xml
<CustomField>
    <fullName>Posted_At__c</fullName>
    <label>Posted At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Raw_Persona_Data__c.field-meta.xml
<CustomField>
    <fullName>Raw_Persona_Data__c</fullName>
    <label>Raw Persona Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Raw_Post_Data__c.field-meta.xml
<CustomField>
    <fullName>Raw_Post_Data__c</fullName>
    <label>Raw Post Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Skip_Create_Case__c.field-meta.xml
<CustomField>
    <fullName>Skip_Create_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Create Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Sprout_Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Sprout_Message_Type__c</fullName>
    <label>Sprout Message Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sprout_Social_Data_Event__c/fields/Unsent_Parent__c.field-meta.xml
<CustomField>
    <fullName>Unsent_Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unsent Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SocialPostResource.cls
@RestResource(urlMapping='/sprout/SocialPost')
global class SocialPostResource {
    
    @HttpPost
    global static void doPost(Social_Post_Request_Param postData, Social_Persona_Request_Param personaData, SocialPostOptions options) {     
        
        

        insert new Sprout_Social_Data_Event__c(
            Raw_Post_Data__c = JSON.serialize(postData),
            Raw_Persona_Data__c = JSON.serialize(personaData),
            Unsent_Parent__c = options.unsentParent,
            Skip_Create_Case__c = options.skipCreateCase,            
            Media_Provider__c = translateProvider(personaData.provider),
            Message_Type__c = postData.messageType,
            Sprout_Message_Type__c = postData.sproutMessageType,
            Persona_Author_Labels__c = personaData.authorLabels,
            Persona_External_Picture_URL__c = personaData.externalPictureURL,
            Persona_Followers__c = personaData.followers,
            Persona_Profile_URL__c = personaData.profileURL,
            Persona_Provider__c = personaData.provider,
            Persona_Real_Name__c = personaData.realName,
            Post_Content__c = postData.content,
            Post_External_ID__c = postData.externalPostId,
            Post_Handle__c = postData.handle,
            Post_Name__c = postData.name,
            Post_Provider__c = translateProvider(postData.provider),
            Post_Tags__c = postData.postTags,
            Post_URL__c = postData.postUrl,
            Posted_At__c = DateTime.valueOfGMT(postData.posted.replace('T', ' ')),
            Customer_Profile_Id__c = postData.customerProfileId,
            Parent_GUID__c = postData.parentGuid,
            Persona_Name__c = personaData.name,
            Persona_External_Id__c = personaData.externalId,
            Persona_First_Name__c = personaData.firstName,
            Persona_Last_Name__c = personaData.lastName,
            Post_Recipient__c = postData.recipient
        );
            
    }

    global class Social_Post_Request_Param {
        String name;
        String content;
        String externalPostId;        
        String messageType; //formerly Message_Type
        String sproutMessageType;
        String customerProfileId; //formerly Customer_Profile_Id
        String handle;        
        String provider;
        String postTags;
        String posted;
        String postUrl;
        String parentGuid; //formerly Parent_GUID
        String recipient;
    }

    global class Social_Persona_Request_Param {
        String name;
        String realName;
        String provider;
        //String mediaProvider;
        String externalId;
        String externalPictureURL;
        String profileURL;
        Integer followers;
        String authorLabels;
        String firstName;
        String lastName;
    }

    global class SocialPostOptions {
        Boolean skipCreateCase;
        Boolean unsentParent;
        private Map<String, Object> getMap() {
            return new Map<String, Object> {
                'skipCreateCase' => this.skipCreateCase,
                'unsentParent' => this.unsentParent
            };
        }
    }

    private static String translateProvider(String providerName) {        
        if (providerName.contains('instagram')) {
           return 'Instagram';
        } else if (providerName.contains('twitter')) {
           return 'Twitter';
        } else if (providerName.contains('whatsapp')) {
           return 'Whatsapp';
        } else if (providerName.contains('linkedin')) {
           return 'LinkedIn';
        } else if (providerName.contains('facebook')) {
           return 'Facebook';
        } else {
           return 'Other';
        }
    }
}