force-app/main/default/objects/Package_Log__c/Package_Log__c.object-meta.xml
<CustomObject>
    <label>Package Log</label>
    <nameField>
        <label>Package Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Package_Log__c/fields/Dump__c.field-meta.xml
<CustomField>
    <fullName>Dump__c</fullName>
    <description>Exception stack trace</description>
    <label>Dump</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/tst_BatchDeletePackageLogs.cls
@isTest
public with sharing class tst_BatchDeletePackageLogs {
    
    @isTest
    static void testDeleteBatch(){
        List<Package_Log__c> logs = new List<Package_Log__c>();
        for(integer i = 1; i < 50; i++){
            Package_Log__c log = new Package_Log__c();
            log.Dump__c = 'log# ' + String.valueOf(i);
            logs.add(log);
        }

        insert logs;

        Test.startTest();

        BatchDeletePackageLogs obj = new BatchDeletePackageLogs();
        Database.executeBatch(obj);
        Test.stopTest();

        List<AggregateResult> numPackageLogsList = [SELECT count(Id) packageLogCount FROM Package_Log__c];

        System.assertEquals(0,numPackageLogsList[0].get('packageLogCount'));
    }
}