force-app/main/default/objects/Package_Log__c/Package_Log__c.object-meta.xml
<CustomObject>
    <label>Package Log</label>
    <nameField>
        <label>Package Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Package_Log__c/fields/Dump__c.field-meta.xml
<CustomField>
    <fullName>Dump__c</fullName>
    <description>Exception stack trace</description>
    <label>Dump</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Package_Log__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Class and line number where exception occured</description>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Exception message</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Exception type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>error</fullName>
            </value>
            <value>
                <fullName>debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Setup_MetaData__mdt/Setup_MetaData__mdt.object-meta.xml
<CustomObject>
    <label>Setup MetaData</label>
    <pluralLabel>Setup MetaData</pluralLabel>
</CustomObject>

force-app/main/default/objects/Setup_MetaData__mdt/fields/Retention_Type__c.field-meta.xml
<CustomField>
    <fullName>Retention_Type__c</fullName>
    <label>Retention Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>errorsOnly</fullName>
                <default>true</default>
                <label>errorsOnly</label>
            </value>
            <value>
                <fullName>allActivity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Setup_MetaData__mdt/fields/Retention_Value__c.field-meta.xml
<CustomField>
    <fullName>Retention_Value__c</fullName>
    <label>Retention Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/packageLogger.cls
public with sharing class packageLogger {

    @testVisible static List<Setup_MetaData__mdt> setupConfigMetadata { 
        get {
            if (setupConfigMetadata == null)
                setupConfigMetadata = [SELECT Label, Retention_Type__c, Retention_Value__c  
                                       FROM Setup_MetaData__mdt
                                       WITH SECURITY_ENFORCED]; 
            return setupConfigMetadata;
        } set; 
    }

    public static void create(String message, String type, String location, String dump) {

        try {
            dmlManager.checkAccess(new Map<String, Map<String, Set<String>>> {
                'Package_Log__c' => new Map<String, Set<String>> {
                    'Read' => new Set<String> {
                        'Dump__c', 'Location__c', 'Message__c', 'Type__c'
                    },
                    'Create' => new Set<String> {
                        'Dump__c', 'Location__c', 'Message__c', 'Type__c'
                    },
                    'Update' => new Set<String> {
                        'Dump__c', 'Location__c', 'Message__c', 'Type__c'
                    }
                }
            });
        
            Set<String> fields = new Set<String> {
                'Id',
                'Retention_Value__c',
                'Retention_Type__c'
            };

            List<Setup_MetaData__mdt> data = [SELECT Id, Retention_Value__c, Retention_Type__c 
                                                FROM Setup_MetaData__mdt 
                                                WITH SECURITY_ENFORCED];
        
            if(Test.isRunningTest()){
                data = setupConfigMetadata;
            }

            Setup_MetaData__mdt setupData = new Setup_MetaData__mdt();

            List<AggregateResult> numPackageLogsList = [SELECT count(Id) packageLogCount FROM Package_Log__c];

            System.debug(setupConfigMetadata.size());

            if (!data.isEmpty()) {
                setupData = data[0];
            }

            if(numPackageLogsList[0].get('packageLogCount') == setupData.get('Retention_Value__c')) {
                delete [SELECT Id 
                        FROM Package_Log__c
                        ORDER BY CreatedDate asc 
                        LIMIT 1];
            }

            insert new Package_Log__c(
                Dump__c = dump.left(131072),
                Location__c = location,
                Message__c = message,
                Type__c = type
            );
        } catch (Exception e) {
            return;
        }
    }

    public static void create(Exception e, Object self){
        packageLogger.create(e, self, null);
    }

    public static void create(Exception e, Object self, String dump){
        String classString = String.valueOf(self);
        String location = classString.left(classString.indexOf(':')) + ':' + String.valueOf(e.getLineNumber());

        if (null == dump){
            dump = e.getStackTraceString();
        }

        packageLogger.create(
            e.getMessage(),
            e.getTypeName(),
            location,
            dump
        );
    }

    public class StrikeException extends Exception {
        public override String getStackTraceString() {
            return super.getCause().getStackTraceString();
        }
    }
}